<?php

namespace ProductBundle\Repository;

/**
 * orderproductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orderproductRepository extends \Doctrine\ORM\EntityRepository
{
}
